### ISSUE TITLE
Use InClusterConfig instead of `kubectl proxy` sidecar

### ISSUE THREAD

**Issue by colemickens** [PalmStoneGames/kube-cert-manager#14]
Since your controller is written in Go, you can just use the [InClusterConfig](https://github.com/kubernetes/kubernetes/blob/master/pkg/client/restclient/config.go#L252) to talk directly to the apiserver with the same serviceaccount that `kubectl proxy` is using now.

**Comment by dominikh** [comment]
Indeed. We were planning to eventually migrate to that solution. It's not a high priority, however, because the kubectl proxy is working rather well.

**Comment by euank** [comment]
FYI I'm picking up this task. I should be done in the next few days.
