### ISSUE TITLE
Only picks up new things

### ISSUE THREAD

**Issue by colemickens** [PalmStoneGames/kube-cert-manager#27]
Looks like if I delete the secret and kick over k-c-m, it doesn't get a cert for the existing ingress.

If I update the ingress, it picks it up.

I guess it should loop over existing ingresses before watching.

**Comment by dominikh** [comment]
Unless Kubernetes's behaviour changed, the first watch operation (with no checkpoint to start from) will replay all existing objects. As such, "watch" and "loop + watch" should behave identically.

**Comment by luna-duclos** [comment]
Any more info on this ? kube-cert-manager seems to pick up everything fine for me, unless kubernetes 1.5 changed the API for this or something ?
