### ISSUE TITLE
documented examples?

### ISSUE THREAD

**Issue by cat5** [PalmStoneGames/kube-cert-manager#38]
Hi, I'm still fairly new to GCE environments (like a few weeks) and wrapping my head around things, but would it be possible to show an example of modifying the deployment with information on 
getting and using the 'GOOGLE_APPLICATION_CREDENTIALS' secret as an volume.

Even an example of what this secret should/would look like in documentation would help newbies like myself.

**Comment by luna-duclos** [comment]
Hello, the challenge providers documentation links to https://kubernetes.io/docs/user-guide/secrets/#using-secrets-as-files-from-a-pod, which documents how to add secrets as files to a pod.
What in this documentation is unclear exactly ?

**Comment by cat5** [comment]
Thanks, I did find that documentation, it helped.
