### ISSUE TITLE
kubectl-proxy:1.5 has not been pushed

### ISSUE THREAD

**Issue by conradev** [PalmStoneGames/kube-cert-manager#44]
The latest version is `1.4`.

**Comment by luna-duclos** [comment]
Yes, I was hoping to get the remaining PRs merged before I made a new release. but that doesn't seem to be worth the wait anymore.

**Comment by luna-duclos** [comment]
We are currently working on integrating some major changes, see #46, #50 and #33, once those are stabilized and working well, a release will be made under the correct new namespace.

Closing this until then.
