### ISSUE TITLE
Is the 0.5.0 build going to be pushed somewhere?

### ISSUE THREAD

**Issue by mlaccetti** [PalmStoneGames/kube-cert-manager#47]
The current 0.3.1 on Docker hub is missing `-default-provider` and `-default-email`.

**Comment by sfrique** [comment]
Same problem

**Comment by MalteJ** [comment]
+1

**Comment by mlaccetti** [comment]
@luna-duclos any word on getting the 0.5.0/1.5.0 stuff out?

**Comment by dominikh** [comment]
There are no plans to push a release at this point. It's recommended that you build your own image if you need the newer changes.

**Comment by luna-duclos** [comment]
We are currently working on integrating some major changes, see #46, #50 and #33, once those are stabilized and working well, a release will be made under the correct new namespace.

**Comment by luna-duclos** [comment]
Closing this until then.
