### ISSUE TITLE
Support cert storage in Kubernetes secrets

### ISSUE THREAD

**Issue by keunwoo** [PalmStoneGames/kube-cert-manager#48]
https://kubernetes.io/docs/user-guide/secrets/

When kube-cert-manager was written originally written, the Kubernetes Secrets API did not exist. However, now that it does, it seems like supporting storage of certs in secrets would be both less setup (no need to register the third party resource) and a more natural mechanism than third party resources. Presumably the legacy method would still be supported to transition smoothly from older installations.

**Comment by colemickens** [comment]
Doesn't the Certificate TPR just hold a reference to a secret that actually holds the cert value? https://github.com/PalmStoneGames/kube-cert-manager/blob/master/processor.go#L681

**Comment by keunwoo** [comment]
Sorry, my previous comment was inaccurate. I guess I was assuming that this project was older than it is, but now that I look at the original commit I see that it was already storing things in secrets:
https://github.com/kelseyhightower/kube-cert-manager/commit/4080840eccda59b054433c093bdd267c0b27c2c2
I've read the code more and now I guess I understand why the third party resource is needed. I'll close this.
