### ISSUE TITLE
KCM shouldn't require the user to create the TPR themselves

### ISSUE THREAD

**Issue by euank** [PalmStoneGames/kube-cert-manager#52]
Other software with associated TPRs (e.g. etcd operator, prometheus operator) create the TPR if it isn't present on first run.

I think it would make sense to do that for KCM too.

**Comment by luna-duclos** [comment]
Agreed, this would be useful

**Comment by euank** [comment]
This project has been deprecated, as have TPRs.
Closing this issue as stale.
