### ISSUE TITLE
logging: use a proper logging library

### ISSUE THREAD

**Issue by euank** [PalmStoneGames/kube-cert-manager#53]
While working on #50, having debug level statements would have been quite helpful! The go stdlib logger just doesn't really cut it for that.

I know that picking a logging library is a massive bikeshed, so let's just pick something and go with it and not argue much. Or just say "let's keep using the stdlib library" and not argue that either.

My preferences in order:

1. github.com/Sirupsen/logrus - The library docker uses, and one of the more popular ones in general I think. I don't really like the logger vs logger.Entry split, but it's still quite usable, popular, and nice. Popularity is a plus for logging libraries since it lets you interoperate with dependencies well, so this seems like a good one to go with.
2. github.com/go-kit/kit/log - This one has picked up some steam recently. It has good semi-structured logging, has levels as an optional addon, and generally looks quite nice.
3. github.com/golang/glog - The library Kubernetes uses for now, though there has been discussion to change it. This allows us to share logging levels and configuration with e.g. client-go... but the glog package is also "over-the-wall" opensource which doesn't take contributions and has package-level functions as the way to interact with it.
4. go.uber.org/zap - Super fast zero allocations. Has good levels and semi-structured-ness. Not many people using it, and we don't really care about speed though, so *shrug*.
5. Stdlib logging library. Nuff said.

Also, for the claims about numbers, I write a snippet of code to determine imports of each logging package. Unfortunately, it counts github forks too so logrus and glog are way over-represented due to forks of docker and Kubernetes. Regardless, the numbers are:

```
	1966	github.com/Sirupsen/logrus
        806	github.com/golang/glog
	70	github.com/go-kit/kit/log
	20	go.uber.org/zap
```
via https://github.com/euank/kitchen-sink/tree/master/goimport-counts#go-importstats

**Comment by luna-duclos** [comment]
I'll have a look at this sometime in the next day or two

**Comment by euank** [comment]
This project's deprecated, closing as stale.
