### ISSUE TITLE
Repeated error logs `Could not find key tls.crt in secret`

### ISSUE THREAD

**Issue by paultiplady** [PalmStoneGames/kube-cert-manager#54]
My kube-cer-manager:0.3.1 deployment appears to have got stuck in a bad state, and is not issuing new certificates.

I'm seeing two of these logs every 30s, and nothing else:

`Error while processing certificate during sync: Error while decoding acme certificate from secret for existing domain : Could not find key tls.crt in secret`

Any suggestions for remedial action or further logs to collect?

**Comment by paultiplady** [comment]
Note this is with GKE provider, in case that's relevant. This was working for a few months without incident prior to this.

**Comment by luna-duclos** [comment]
It seems that kcm is stuck dealing with an incorrect secret, could you check your k8s deployment and see if there are any secrets missing a tls.crt key ?

**Comment by paultiplady** [comment]
All of my Secrets with the annotation `{"stable.k8s.psg.io/kcm":"true"}` have both tls.crt and tls.key.

I do have many Secrets without that annotation though. Could it be getting confused there? In particular the `for existing domain :` log is suspicious, it's normally `for existing domain <domain>:` which suggests kcm doesn't have a domain for this lookup.

**Comment by luna-duclos** [comment]
Could you clear kcm's data volume ? This'll cause certs to get rerequested instead of refreshed, but unless you're close to the quota, that shouldn't be an issue.

**Comment by paultiplady** [comment]
Digging through my Certificates individually, it looks like I might actually be hitting a k8s bug:

https://github.com/kubernetes/kubernetes/issues/44182

Clearing out the invalid TPRs seems to have got things back on track.

**Comment by luna-duclos** [comment]
I'll keep an eye out on that issue, do you have any idea how the corrupt certificate was initially created, was it by KCM ?

**Comment by paultiplady** [comment]
I created it using a hand-rolled ThirdPartyResource on top of `pykube`,
which it turns out doesn't really support TPRs.

**Comment by luna-duclos** [comment]
Sounds like this isn't an issue with kcm then, good to hear :)
