### ISSUE TITLE
Compare features with the original kube-cert-manager

### ISSUE THREAD

**Issue by ahmetb** [PalmStoneGames/kube-cert-manager#55]
> This project is loosely based on https://github.com/kelseyhightower/kube-cert-manager It took over most of its documentation, license, as well as the general approach to how things work.
> The code itself however, was entirely reimplemented to use xenolf/lego as the basis, instead of reimplementing an ACME client and DNS plugins.

This helps, but doesn't tell me:

- why use this fork instead of the original project
- is using the original project still fine, or does this fork make that obsolete
- what features are different and why (telling you used `xenolf/lego` or reimplemented everything doesn't really ring a bell for me)

**Comment by luna-duclos** [comment]
You can find the list of features of this project here:

https://github.com/PalmStoneGames/kube-cert-manager#features

and of the kelseyhightower project:

https://github.com/kelseyhightower/kube-cert-manager#features
