### ISSUE TITLE
Certificate not being picked up by watch in master branch

### ISSUE THREAD

**Issue by ahmetb** [PalmStoneGames/kube-cert-manager#65]
I have deployed kube-cert-manager from the tip of master branch today and configured with my cloudflare API key. Output from the kcm pod shows healthy status:

```
$ kubectl logs -f kube-cert-manager-2773976669-52w89 kube-cert-manager
2017/04/24 20:39:02 Starting Kubernetes Certificate Controller...
2017/04/24 20:39:02 Kubernetes Certificate Controller started successfully.
2017/04/24 20:39:02 Watching certificates and ingresses in all namespaces
```

Before started pod, I did `kubectl apply -f k8s/certificate-type.yaml`. 

Then I did `kubectl apply` for a Certificate resource as follows:

```yml
apiVersion: "stable.k8s.psg.io/v1"
kind: "Certificate"
metadata:
  name: "ng-kcm"
spec:
  domain: "ng.alp.im"
  email: "myemailaddress@gmail.com"
  provider: "cloudflare"
  secretName: ng-kcm-tls
```

However I don't see any of the logs about this Certificate getting picked up (like the sample output in https://github.com/PalmStoneGames/kube-cert-manager/blob/master/docs/create-a-certificate.md). 

No secrets are created either so it probably doesn’t work.

But the certificate resource is there:

```
$ kubectl get certificate
NAME      KIND
ng-kcm    Certificate.v1.stable.k8s.psg.io
```

Restarting does not help. I am basically stuck at this point.

**Comment by luna-duclos** [comment]
Hello, could you try this again on the latest stable version ? v0.4.0, I've added tags and links to the docs for that version on the main page.

**Comment by ahmetb** [comment]
@luna-duclos Things ~~progressed~~ worked once I built from v0.4.0. Thanks. I'll leave it up to you to what to do with this issue.

**Comment by dstufft** [comment]
I'm also having this problem-- unfortunately switching to v0.4.0 isn't an option for me, because I need support for SANs which appears to only be in the `master` branch.
