### ISSUE TITLE
Possible to implement without persistent volume?

### ISSUE THREAD

**Issue by ahmetb** [PalmStoneGames/kube-cert-manager#67]
Is there a way this project can not use a persistent volume for a single file (boltdb database)?

If there's a way to efficiently store this database on some Kubernetes API objects, this would enable more environments that lack persistent volume support such as gcePersistentDisk. Also it would mean one less moving part.

I'd love to see if it's possible to reuse the API’s storage capabilities to implement kube-cert-manager without a persistent disk.

**Comment by luna-duclos** [comment]
This is unfortunately not really possible without basterdizing an API object to turn it into a persistent disk somehow, a persistent disk is the correct solution here.
