### ISSUE TITLE
How to setup automatic renewal of my LetsEncrypt certs by kube-cert-manager?

### ISSUE THREAD

**Issue by roshan-mr** [PalmStoneGames/kube-cert-manager#74]
Hi,

I have successfully configured kube-cert-manager and I am terminating the SSL/TLS in Ingress. I would like to know how can I configure the renewal of certs automatically. Is it already in place or does it requires additional configuration. 

Regards,
Muhammed Roshan

**Comment by rosskukulinski** [comment]
Hi @roshan-mr - this is already built in and there's nothing you need to do.  I do want to note that you'll likely get an email letting you know the certificate is going to expire.  The default refresh interval for KCM is less than the email warning - see #43.
