### ISSUE TITLE
kubernetes 1.4 no longer validates the certificate resource

### ISSUE THREAD

**Issue by groob** [PalmStoneGames/kube-cert-manager#9]
Getting the error 

```
error validating data: the server could not find the requested resource; if you choose to ignore these errors, turn validation off with --validate=false
```

trying to create a new certificate resource on a 1.4 cluster.

setting `--validate=false` does appear to resolve the issue for now. 

The new third party resource requirements are documented in this k8s PR https://github.com/kubernetes/kubernetes/commit/620cc66ead8256ad27fceb61d5d37e6d6c0c3efc

**Comment by dominikh** [comment]
Silly question, but are you sure you've imported `k8s/certificate.yaml` in your new cluster?

**Comment by groob** [comment]
Yes, I have:

```
Error from server: error when creating "certmanager/certificate.yaml": thirdpartyresources.extensions "certificate.stable.k8s.psg.io" already exists
```

**Comment by luna-duclos** [comment]
I've been unable to reproduce this in my own 1.4 cluster. Can you get in touch with me on slack ?

**Comment by luna-duclos** [comment]
After a hangouts call, we've discovered that running kubectl 1.3 with a 1.4 cluster causes these problems.
